rnn300_00 val_acc = 0.76264
drop_rate =0.4 seed = 0
model.add(Bidirectional(LSTM(128, activation='tanh', kernel_initializer='Orthogonal', recurrent_initializer='Orthogonal', return_sequences=True, unit_forget_bias=False, dropout=drop_rate, recurrent_dropout=drop_rate), merge_mode='sum'))
model.add(Bidirectional(LSTM(128, activation='tanh', kernel_initializer='Orthogonal', recurrent_initializer='Orthogonal', return_sequences=False, unit_forget_bias=False, dropout=drop_rate, recurrent_dropout=drop_rate), merge_mode='sum'))
model.add(Dense(256))
model.add(Dropout(drop_rate))
model.add(LeakyReLU(0.2))
model.add(Dense(256))
model.add(Dropout(drop_rate))
model.add(LeakyReLU(0.2))
model.add(Dense(1))

rnn300_01 val_acc = 0.76252
drop_rate =0.4 seed = 1
model.add(Bidirectional(LSTM(128, activation='tanh', kernel_initializer='Orthogonal', recurrent_initializer='Orthogonal', return_sequences=True, unit_forget_bias=False, dropout=drop_rate, recurrent_dropout=drop_rate), merge_mode='sum'))
model.add(Bidirectional(LSTM(128, activation='tanh', kernel_initializer='Orthogonal', recurrent_initializer='Orthogonal', return_sequences=True, unit_forget_bias=False, dropout=drop_rate, recurrent_dropout=drop_rate), merge_mode='sum'))
model.add(Bidirectional(LSTM(128, activation='tanh', kernel_initializer='Orthogonal', recurrent_initializer='Orthogonal', return_sequences=True, unit_forget_bias=False, dropout=drop_rate, recurrent_dropout=drop_rate), merge_mode='sum'))
model.add(Bidirectional(LSTM(128, activation='tanh', kernel_initializer='Orthogonal', recurrent_initializer='Orthogonal', return_sequences=False, unit_forget_bias=False, dropout=drop_rate, recurrent_dropout=drop_rate), merge_mode='sum'))
model.add(Dense(256))
model.add(Dropout(drop_rate))
model.add(LeakyReLU(0.2))
model.add(Dense(256))
model.add(Dropout(drop_rate))
model.add(LeakyReLU(0.2))
model.add(Dense(1))

rnn300_02 val_acc = 
drop_rate =0.4 seed = 2
model.add(Bidirectional(LSTM(256, activation='tanh', kernel_initializer='Orthogonal', recurrent_initializer='Orthogonal', return_sequences=True, unit_forget_bias=False, dropout=drop_rate, recurrent_dropout=drop_rate), merge_mode='sum'))
model.add(Bidirectional(LSTM(256, activation='tanh', kernel_initializer='Orthogonal', recurrent_initializer='Orthogonal', return_sequences=True, unit_forget_bias=False, dropout=drop_rate, recurrent_dropout=drop_rate), merge_mode='sum'))
model.add(Bidirectional(LSTM(256, activation='tanh', kernel_initializer='Orthogonal', recurrent_initializer='Orthogonal', return_sequences=True, unit_forget_bias=False, dropout=drop_rate, recurrent_dropout=drop_rate), merge_mode='sum'))
model.add(Bidirectional(LSTM(256, activation='tanh', kernel_initializer='Orthogonal', recurrent_initializer='Orthogonal', return_sequences=False, unit_forget_bias=False, dropout=drop_rate, recurrent_dropout=drop_rate), merge_mode='sum'))
model.add(Dense(256))
model.add(Dropout(drop_rate))
model.add(LeakyReLU(0.2))
model.add(Dense(256))
model.add(Dropout(drop_rate))
model.add(LeakyReLU(0.2))
model.add(Dense(256))
model.add(Dropout(drop_rate))
model.add(LeakyReLU(0.2))
model.add(Dense(256))
model.add(Dropout(drop_rate))
model.add(LeakyReLU(0.2))
model.add(Dense(256))
model.add(Dropout(drop_rate))
model.add(LeakyReLU(0.2))
model.add(Dense(1))

rnn300_03 val_acc = 0.7626
drop_rate =0.4 seed = 3
model.add(Bidirectional(LSTM(256, activation='tanh', kernel_initializer='Orthogonal', recurrent_initializer='Orthogonal', return_sequences=True, unit_forget_bias=False, dropout=drop_rate, recurrent_dropout=drop_rate), merge_mode='sum'))
model.add(Bidirectional(LSTM(256, activation='tanh', kernel_initializer='Orthogonal', recurrent_initializer='Orthogonal', return_sequences=True, unit_forget_bias=False, dropout=drop_rate, recurrent_dropout=drop_rate), merge_mode='sum'))
model.add(Bidirectional(LSTM(256, activation='tanh', kernel_initializer='Orthogonal', recurrent_initializer='Orthogonal', return_sequences=False, unit_forget_bias=False, dropout=drop_rate, recurrent_dropout=drop_rate), merge_mode='sum'))
model.add(Dense(512))
model.add(Dropout(drop_rate))
model.add(LeakyReLU(0.2))
model.add(Dense(512))
model.add(Dropout(drop_rate))
model.add(LeakyReLU(0.2))
model.add(Dense(512))
model.add(Dropout(drop_rate))
model.add(LeakyReLU(0.2))
model.add(Dense(1))

rnn300_06 val_acc = 
drop_rate =0.4 seed = 6
model.add(Bidirectional(GRU(256, activation='tanh', kernel_initializer='Orthogonal', recurrent_initializer='Orthogonal', return_sequences=True, dropout=drop_rate, recurrent_dropout=drop_rate), merge_mode='sum'))
model.add(BatchNormalization())
model.add(Bidirectional(GRU(256, activation='tanh', kernel_initializer='Orthogonal', recurrent_initializer='Orthogonal', return_sequences=True, dropout=drop_rate, recurrent_dropout=drop_rate), merge_mode='sum'))
model.add(BatchNormalization())
model.add(Bidirectional(GRU(256, activation='tanh', kernel_initializer='Orthogonal', recurrent_initializer='Orthogonal', return_sequences=False, dropout=drop_rate, recurrent_dropout=drop_rate), merge_mode='sum'))
model.add(BatchNormalization())
model.add(Dense(256))
model.add(Dropout(drop_rate))
model.add(LeakyReLU(0.2))
model.add(BatchNormalization())
model.add(Dense(256))
model.add(Dropout(drop_rate))
model.add(LeakyReLU(0.2))
model.add(BatchNormalization())
model.add(Dense(256))
model.add(Dropout(drop_rate))
model.add(LeakyReLU(0.2))
model.add(BatchNormalization())
model.add(Dense(1))
############################
rnn250_00 val_acc = 0.76307 public_score = 0.75970 private_score = 0.75390
drop_rate =0.35 seed = 19990107
model.add(Bidirectional(LSTM(128, activation='tanh', kernel_initializer='Orthogonal', recurrent_initializer='Orthogonal', return_sequences=True, unit_forget_bias=False, dropout=drop_rate, recurrent_dropout=drop_rate), merge_mode='sum'))
model.add(Bidirectional(LSTM(128, activation='tanh', kernel_initializer='Orthogonal', recurrent_initializer='Orthogonal', return_sequences=False, unit_forget_bias=False, dropout=drop_rate, recurrent_dropout=drop_rate), merge_mode='sum'))
model.add(Dense(256))
model.add(Dropout(drop_rate))
model.add(LeakyReLU(0.2))
model.add(Dense(256))
model.add(Dropout(drop_rate))
model.add(LeakyReLU(0.2))
model.add(Dense(1))


rnn250_01 val_acc = 0.76256 public_score = 0.76180 private_score = 0.75660
drop_rate =0.35 seed = 19990108
model.add(Bidirectional(LSTM(128, activation='tanh', kernel_initializer='Orthogonal', recurrent_initializer='Orthogonal', return_sequences=True, unit_forget_bias=False, dropout=drop_rate, recurrent_dropout=drop_rate), merge_mode='sum'))
model.add(Bidirectional(LSTM(128, activation='tanh', kernel_initializer='Orthogonal', recurrent_initializer='Orthogonal', return_sequences=True, unit_forget_bias=False, dropout=drop_rate, recurrent_dropout=drop_rate), merge_mode='sum'))
model.add(Bidirectional(LSTM(128, activation='tanh', kernel_initializer='Orthogonal', recurrent_initializer='Orthogonal', return_sequences=True, unit_forget_bias=False, dropout=drop_rate, recurrent_dropout=drop_rate), merge_mode='sum'))
model.add(Bidirectional(LSTM(128, activation='tanh', kernel_initializer='Orthogonal', recurrent_initializer='Orthogonal', return_sequences=False, unit_forget_bias=False, dropout=drop_rate, recurrent_dropout=drop_rate), merge_mode='sum'))
model.add(Dense(256))
model.add(Dropout(drop_rate))
model.add(LeakyReLU(0.2))
model.add(Dense(256))
model.add(Dropout(drop_rate))
model.add(LeakyReLU(0.2))
model.add(Dense(1))

rnn250_02 val_acc = 0.76159 public_score = 0.75840 private_score = 0.75630
drop_rate =0.4 seed = 2
model.add(Bidirectional(LSTM(256, activation='tanh', kernel_initializer='Orthogonal', recurrent_initializer='Orthogonal', return_sequences=True, unit_forget_bias=False, dropout=drop_rate, recurrent_dropout=drop_rate), merge_mode='sum'))
model.add(Bidirectional(LSTM(256, activation='tanh', kernel_initializer='Orthogonal', recurrent_initializer='Orthogonal', return_sequences=True, unit_forget_bias=False, dropout=drop_rate, recurrent_dropout=drop_rate), merge_mode='sum'))
model.add(Bidirectional(LSTM(256, activation='tanh', kernel_initializer='Orthogonal', recurrent_initializer='Orthogonal', return_sequences=True, unit_forget_bias=False, dropout=drop_rate, recurrent_dropout=drop_rate), merge_mode='sum'))
model.add(Bidirectional(LSTM(256, activation='tanh', kernel_initializer='Orthogonal', recurrent_initializer='Orthogonal', return_sequences=False, unit_forget_bias=False, dropout=drop_rate, recurrent_dropout=drop_rate), merge_mode='sum'))
model.add(Dense(256))
model.add(Dropout(drop_rate))
model.add(LeakyReLU(0.2))
model.add(Dense(256))
model.add(Dropout(drop_rate))
model.add(LeakyReLU(0.2))
model.add(Dense(256))
model.add(Dropout(drop_rate))
model.add(LeakyReLU(0.2))
model.add(Dense(256))
model.add(Dropout(drop_rate))
model.add(LeakyReLU(0.2))
model.add(Dense(256))
model.add(Dropout(drop_rate))
model.add(LeakyReLU(0.2))
model.add(Dense(1))

rnn250_03 val_acc = 0.76336 public_score = 0.76430 private_score = 0.75590
drop_rate =4 seed = 3
model.add(Bidirectional(LSTM(256, activation='tanh', kernel_initializer='Orthogonal', recurrent_initializer='Orthogonal', return_sequences=True, unit_forget_bias=False, dropout=drop_rate, recurrent_dropout=drop_rate), merge_mode='sum'))
model.add(Bidirectional(LSTM(256, activation='tanh', kernel_initializer='Orthogonal', recurrent_initializer='Orthogonal', return_sequences=True, unit_forget_bias=False, dropout=drop_rate, recurrent_dropout=drop_rate), merge_mode='sum'))
model.add(Bidirectional(LSTM(256, activation='tanh', kernel_initializer='Orthogonal', recurrent_initializer='Orthogonal', return_sequences=False, unit_forget_bias=False, dropout=drop_rate, recurrent_dropout=drop_rate), merge_mode='sum'))
model.add(Dense(512))
model.add(Dropout(drop_rate))
model.add(LeakyReLU(0.2))
model.add(Dense(512))
model.add(Dropout(drop_rate))
model.add(LeakyReLU(0.2))
model.add(Dense(512))
model.add(Dropout(drop_rate))
model.add(LeakyReLU(0.2))
model.add(Dense(1))

rnn250_04 val_acc = 0.76638 public_score = 0.75880
drop_rate =0.4 seed = 4
model.add(Bidirectional(GRU(256, activation='tanh', kernel_initializer='Orthogonal', recurrent_initializer='Orthogonal', return_sequences=True, dropout=drop_rate, recurrent_dropout=drop_rate), merge_mode='sum'))
model.add(Bidirectional(GRU(256, activation='tanh', kernel_initializer='Orthogonal', recurrent_initializer='Orthogonal', return_sequences=True, dropout=drop_rate, recurrent_dropout=drop_rate), merge_mode='sum'))
model.add(Bidirectional(GRU(256, activation='tanh', kernel_initializer='Orthogonal', recurrent_initializer='Orthogonal', return_sequences=False, dropout=drop_rate, recurrent_dropout=drop_rate), merge_mode='sum'))
model.add(Dense(256))
model.add(Dropout(drop_rate))
model.add(LeakyReLU(0.2))
model.add(Dense(256))
model.add(Dropout(drop_rate))
model.add(LeakyReLU(0.2))
model.add(Dense(256))
model.add(Dropout(drop_rate))
model.add(LeakyReLU(0.2))
model.add(Dense(256))
model.add(Dropout(drop_rate))
model.add(LeakyReLU(0.2))
model.add(Dense(256))
model.add(Dropout(drop_rate))
model.add(LeakyReLU(0.2))
model.add(Dense(1))

rnn250_05 val_acc = 0.76201 public_score = 0.75960 private_score = 0.75510
drop_rate =0.4 seed = 5
model.add(Bidirectional(GRU(128, activation='tanh', kernel_initializer='Orthogonal', recurrent_initializer='Orthogonal', return_sequences=True, dropout=drop_rate, recurrent_dropout=drop_rate), merge_mode='sum'))
model.add(Bidirectional(GRU(128, activation='tanh', kernel_initializer='Orthogonal', recurrent_initializer='Orthogonal', return_sequences=True, dropout=drop_rate, recurrent_dropout=drop_rate), merge_mode='sum'))
model.add(Bidirectional(GRU(128, activation='tanh', kernel_initializer='Orthogonal', recurrent_initializer='Orthogonal', return_sequences=False, dropout=drop_rate, recurrent_dropout=drop_rate), merge_mode='sum'))
model.add(Dense(256))
model.add(Dropout(drop_rate))
model.add(LeakyReLU(0.2))
model.add(Dense(256))
model.add(Dropout(drop_rate))
model.add(LeakyReLU(0.2))
model.add(Dense(256))
model.add(Dropout(drop_rate))
model.add(LeakyReLU(0.2))
model.add(Dense(256))
model.add(Dropout(drop_rate))
model.add(LeakyReLU(0.2))
model.add(Dense(1))

rnn250_06 val_acc = 0.76189 public_score = 0.75530 private_score = 0.75960
drop_rate =0.4 seed = 6 
model.add(Bidirectional(GRU(256, activation='tanh', kernel_initializer='Orthogonal', recurrent_initializer='Orthogonal', return_sequences=True, dropout=drop_rate, recurrent_dropout=drop_rate), merge_mode='sum'))
model.add(BatchNormalization())
model.add(Bidirectional(GRU(256, activation='tanh', kernel_initializer='Orthogonal', recurrent_initializer='Orthogonal', return_sequences=True, dropout=drop_rate, recurrent_dropout=drop_rate), merge_mode='sum'))
model.add(BatchNormalization())
model.add(Bidirectional(GRU(256, activation='tanh', kernel_initializer='Orthogonal', recurrent_initializer='Orthogonal', return_sequences=False, dropout=drop_rate, recurrent_dropout=drop_rate), merge_mode='sum'))
model.add(BatchNormalization())
model.add(Dense(256))
model.add(Dropout(drop_rate))
model.add(LeakyReLU(0.2))
model.add(BatchNormalization())
model.add(Dense(256))
model.add(Dropout(drop_rate))
model.add(LeakyReLU(0.2))
model.add(BatchNormalization())
model.add(Dense(256))
model.add(Dropout(drop_rate))
model.add(LeakyReLU(0.2))
model.add(BatchNormalization())
model.add(Dense(1))

rnn250_07 val_acc = 0.76059 public_score = 0.76320 private_score = 0.75560
drop_rate =0.4 seed = 7
model.add(Bidirectional(LSTM(256, activation='tanh', kernel_initializer='Orthogonal', recurrent_initializer='Orthogonal', return_sequences=True, unit_forget_bias=False, dropout=drop_rate, recurrent_dropout=drop_rate), merge_mode='sum'))
model.add(BatchNormalization())
model.add(Bidirectional(LSTM(256, activation='tanh', kernel_initializer='Orthogonal', recurrent_initializer='Orthogonal', return_sequences=True, unit_forget_bias=False, dropout=drop_rate, recurrent_dropout=drop_rate), merge_mode='sum'))
model.add(BatchNormalization())
model.add(Bidirectional(LSTM(256, activation='tanh', kernel_initializer='Orthogonal', recurrent_initializer='Orthogonal', return_sequences=False, unit_forget_bias=False, dropout=drop_rate, recurrent_dropout=drop_rate), merge_mode='sum'))
model.add(BatchNormalization())
model.add(Dense(512))
model.add(Dropout(drop_rate))
model.add(LeakyReLU(0.2))
model.add(BatchNormalization())
model.add(Dense(512))
model.add(Dropout(drop_rate))
model.add(LeakyReLU(0.2))
model.add(BatchNormalization())
model.add(Dense(512))
model.add(Dropout(drop_rate))
model.add(LeakyReLU(0.2))
model.add(BatchNormalization())
model.add(Dense(1))
####################################
rnn00 val_acc = 0.76138  ####
drop_rate =0.3 seed = 19990107
model.add(Bidirectional(LSTM(256, activation='tanh', kernel_initializer='Orthogonal', recurrent_initializer='Orthogonal', return_sequences=True, unit_forget_bias=False, dropout=drop_rate, recurrent_dropout=drop_rate), merge_mode='sum'))
model.add(Bidirectional(LSTM(256, activation='tanh', kernel_initializer='Orthogonal', recurrent_initializer='Orthogonal', return_sequences=False, unit_forget_bias=False, dropout=drop_rate, recurrent_dropout=drop_rate), merge_mode='sum'))
model.add(Dense(1024))
model.add(LeakyReLU(0.2))
model.add(Dropout(drop_rate))
model.add(Dense(1024))
model.add(LeakyReLU(0.2))
model.add(Dropout(drop_rate))
model.add(Dense(1024))
model.add(LeakyReLU(0.2))
model.add(Dropout(drop_rate))
model.add(Dense(1024))
model.add(LeakyReLU(0.2))
model.add(Dropout(drop_rate))
model.add(Dense(1024))
model.add(LeakyReLU(0.2))
model.add(Dropout(drop_rate))
model.add(Dense(1))

rnn03 val_acc = 0.76172 ###
drop_rate =0.3 seed = 19990107
model.add(Bidirectional(LSTM(256, activation='tanh', kernel_initializer='Orthogonal', recurrent_initializer='Orthogonal', return_sequences=True, unit_forget_bias=False, dropout=drop_rate, recurrent_dropout=drop_rate), merge_mode='sum'))
model.add(BatchNormalization())
model.add(Bidirectional(LSTM(256, activation='tanh', kernel_initializer='Orthogonal', recurrent_initializer='Orthogonal', return_sequences=False, unit_forget_bias=False, dropout=drop_rate, recurrent_dropout=drop_rate), merge_mode='sum'))
model.add(Dense(2048))
model.add(BatchNormalization())
model.add(LeakyReLU(0.2))
model.add(Dropout(drop_rate))
model.add(Dense(2048))
model.add(BatchNormalization())
model.add(LeakyReLU(0.2))
model.add(Dropout(drop_rate))
model.add(Dense(1))

rnn04 val_acc= 0.76071 ###
drop_rate =0.3 seed = 406668888
model.add(Bidirectional(LSTM(128, activation='tanh', kernel_initializer='Orthogonal', recurrent_initializer='Orthogonal', return_sequences=True, unit_forget_bias=False, dropout=drop_rate, recurrent_dropout=drop_rate), merge_mode='sum'))
model.add(Bidirectional(LSTM(128, activation='tanh', kernel_initializer='Orthogonal', recurrent_initializer='Orthogonal', return_sequences=True, unit_forget_bias=False, dropout=drop_rate, recurrent_dropout=drop_rate), merge_mode='sum'))
model.add(Bidirectional(LSTM(128, activation='tanh', kernel_initializer='Orthogonal', recurrent_initializer='Orthogonal', return_sequences=True, unit_forget_bias=False, dropout=drop_rate, recurrent_dropout=drop_rate), merge_mode='sum'))
model.add(Bidirectional(LSTM(128, activation='tanh', kernel_initializer='Orthogonal', recurrent_initializer='Orthogonal', return_sequences=False, unit_forget_bias=False, dropout=drop_rate, recurrent_dropout=drop_rate), merge_mode='sum'))
model.add(Dense(1024))
model.add(LeakyReLU(0.2))
model.add(Dropout(drop_rate))
model.add(Dense(1024))
model.add(LeakyReLU(0.2))
model.add(Dropout(drop_rate))
model.add(Dense(1))

rnn05 val_acc= 0.76592 public_score= 0.75750  ###
drop_rate =0.3 seed = 406668889
model.add(Bidirectional(LSTM(128, activation='tanh', kernel_initializer='Orthogonal', recurrent_initializer='Orthogonal', return_sequences=True, unit_forget_bias=False, dropout=drop_rate, recurrent_dropout=drop_rate), merge_mode='sum'))
model.add(Bidirectional(LSTM(128, activation='tanh', kernel_initializer='Orthogonal', recurrent_initializer='Orthogonal', return_sequences=True, unit_forget_bias=False, dropout=drop_rate, recurrent_dropout=drop_rate), merge_mode='sum'))
model.add(Bidirectional(LSTM(128, activation='tanh', kernel_initializer='Orthogonal', recurrent_initializer='Orthogonal', return_sequences=True, unit_forget_bias=False, dropout=drop_rate, recurrent_dropout=drop_rate), merge_mode='sum'))
model.add(Bidirectional(LSTM(128, activation='tanh', kernel_initializer='Orthogonal', recurrent_initializer='Orthogonal', return_sequences=False, unit_forget_bias=False, dropout=drop_rate, recurrent_dropout=drop_rate), merge_mode='sum'))
model.add(Dense(1024))
model.add(LeakyReLU(0.2))
model.add(Dropout(drop_rate))
model.add(Dense(1024))
model.add(LeakyReLU(0.2))
model.add(Dropout(drop_rate))
model.add(Dense(1024))
model.add(LeakyReLU(0.2))
model.add(Dropout(drop_rate))
model.add(Dense(1024))
model.add(LeakyReLU(0.2))
model.add(Dropout(drop_rate))
model.add(Dense(1024))
model.add(LeakyReLU(0.2))
model.add(Dropout(drop_rate))
model.add(Dense(1))

rnn09 val_acc = 0.7655 ###
drop_rate =0.3 seed = 428
model.add(Bidirectional(GRU(256, activation='tanh', kernel_initializer='Orthogonal', recurrent_initializer='Orthogonal', return_sequences=True, dropout=drop_rate, recurrent_dropout=drop_rate), merge_mode='sum'))
model.add(Bidirectional(GRU(256, activation='tanh', kernel_initializer='Orthogonal', recurrent_initializer='Orthogonal', return_sequences=True, dropout=drop_rate, recurrent_dropout=drop_rate), merge_mode='sum'))
model.add(Bidirectional(GRU(256, activation='tanh', kernel_initializer='Orthogonal', recurrent_initializer='Orthogonal', return_sequences=False, dropout=drop_rate, recurrent_dropout=drop_rate), merge_mode='sum'))
model.add(Dense(1024))
model.add(LeakyReLU(0.2))
model.add(Dropout(drop_rate))
model.add(Dense(1024))
model.add(LeakyReLU(0.2))
model.add(Dropout(drop_rate))
model.add(Dense(1))


#####################################
rnn01 val_acc = 
drop_rate =0.3 seed = 706
model.add(Bidirectional(LSTM(256, activation='tanh', kernel_initializer='Orthogonal', recurrent_initializer='Orthogonal', return_sequences=True, unit_forget_bias=False, dropout=drop_rate, recurrent_dropout=drop_rate), merge_mode='sum'))
model.add(Bidirectional(LSTM(256, activation='tanh', kernel_initializer='Orthogonal', recurrent_initializer='Orthogonal', return_sequences=True, unit_forget_bias=False, dropout=drop_rate, recurrent_dropout=drop_rate), merge_mode='sum'))
model.add(Bidirectional(LSTM(256, activation='tanh', kernel_initializer='Orthogonal', recurrent_initializer='Orthogonal', return_sequences=True, unit_forget_bias=False, dropout=drop_rate, recurrent_dropout=drop_rate), merge_mode='sum'))
model.add(Bidirectional(LSTM(256, activation='tanh', kernel_initializer='Orthogonal', recurrent_initializer='Orthogonal', return_sequences=True, unit_forget_bias=False, dropout=drop_rate, recurrent_dropout=drop_rate), merge_mode='sum'))
model.add(Bidirectional(LSTM(256, activation='tanh', kernel_initializer='Orthogonal', recurrent_initializer='Orthogonal', return_sequences=True, unit_forget_bias=False, dropout=drop_rate, recurrent_dropout=drop_rate), merge_mode='sum'))
model.add(Bidirectional(LSTM(256, activation='tanh', kernel_initializer='Orthogonal', recurrent_initializer='Orthogonal', return_sequences=False, unit_forget_bias=False, dropout=drop_rate, recurrent_dropout=drop_rate), merge_mode='sum'))
model.add(Dense(1024))
model.add(LeakyReLU(0.2))
model.add(Dropout(drop_rate))
model.add(Dense(1024))
model.add(LeakyReLU(0.2))
model.add(Dropout(drop_rate))
model.add(Dense(1))

rnn06 val_acc = 0.7652
drop_rate =0.3 seed = 123
model.add(Bidirectional(LSTM(256, activation='tanh', kernel_initializer='Orthogonal', recurrent_initializer='Orthogonal', return_sequences=True, unit_forget_bias=False, dropout=drop_rate, recurrent_dropout=drop_rate), merge_mode='sum'))
model.add(Bidirectional(LSTM(256, activation='tanh', kernel_initializer='Orthogonal', recurrent_initializer='Orthogonal', return_sequences=False, unit_forget_bias=False, dropout=drop_rate, recurrent_dropout=drop_rate), merge_mode='sum'))
model.add(Dense(1024))
model.add(LeakyReLU(0.2))
model.add(Dropout(drop_rate))
model.add(Dense(1024))
model.add(LeakyReLU(0.2))
model.add(Dropout(drop_rate))
model.add(Dense(2))
model.add(Activation('sigmoid'))
adam = optimizers.Adam(lr=0.002, clipvalue=1, beta_1=0.9, beta_2=0.999, epsilon=None, decay=0.0)

rnn08 val_acc = 0.76391 public_score = 0.75860
drop_rate =0.3 seed = 429
model.add(Bidirectional(LSTM(256, activation='tanh', kernel_initializer='Orthogonal', recurrent_initializer='Orthogonal', return_sequences=True, unit_forget_bias=False, dropout=drop_rate, recurrent_dropout=drop_rate), merge_mode='sum'))
model.add(Bidirectional(LSTM(256, activation='tanh', kernel_initializer='Orthogonal', recurrent_initializer='Orthogonal', return_sequences=True, unit_forget_bias=False, dropout=drop_rate, recurrent_dropout=drop_rate), merge_mode='sum'))
model.add(Bidirectional(LSTM(256, activation='tanh', kernel_initializer='Orthogonal', recurrent_initializer='Orthogonal', return_sequences=False, unit_forget_bias=False, dropout=drop_rate, recurrent_dropout=drop_rate), merge_mode='sum'))
model.add(Dense(1024))
model.add(LeakyReLU(0.2))
model.add(Dropout(drop_rate))
model.add(Dense(1024))
model.add(LeakyReLU(0.2))
model.add(Dropout(drop_rate))
model.add(Dense(1))


rnn02 val_acc = 0.76647 public_score = 0.75740
drop_rate =0.3 seed = 19990106
model.add(Bidirectional(LSTM(128, activation='tanh', kernel_initializer='Orthogonal', recurrent_initializer='Orthogonal', return_sequences=True, unit_forget_bias=False, dropout=drop_rate, recurrent_dropout=drop_rate), merge_mode='sum'))
model.add(Bidirectional(LSTM(128, activation='tanh', kernel_initializer='Orthogonal', recurrent_initializer='Orthogonal', return_sequences=True, unit_forget_bias=False, dropout=drop_rate, recurrent_dropout=drop_rate), merge_mode='sum'))
model.add(Bidirectional(LSTM(128, activation='tanh', kernel_initializer='Orthogonal', recurrent_initializer='Orthogonal', return_sequences=False, unit_forget_bias=False, dropout=drop_rate, recurrent_dropout=drop_rate), merge_mode='sum'))
model.add(Dense(1024))
model.add(LeakyReLU(0.2))
model.add(Dropout(drop_rate))
model.add(Dense(1024))
model.add(LeakyReLU(0.2))
model.add(Dropout(drop_rate))
model.add(Dense(2))
